### ISSUE TITLE
sample input & output 可以多組一些。 @(add problem)

### ISSUE THREAD

**Issue by ericmina83** [NTUST-GameLab/Online-Judge#4]
因學弟至少會在一題中放一組正解和一組錯誤的解（輸入錯誤時的結果），所以我覺得至少要有兩組以上的 sample input & output 欄位。

**Comment by grass0916** [comment]
上次一開會後，決議讓學生以循環讀取 input 的方式，所以此建議將關閉不採用。

**Comment by grass0916** [comment]
@1shan
